# Generated by Django 5.0.6 on 2024-07-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_covariancedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='covariancedata',
            name='calculation_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
