# Generated by Django 5.0.6 on 2024-07-01 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_covariancedata_calculation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covariancedata',
            name='calculation_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
