# Generated by Django 5.0.6 on 2024-07-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_alter_covariancedata_calculation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SP500Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
            ],
        ),
    ]
