# Generated by Django 5.0.6 on 2024-07-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_sp500ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('enterprise_value', models.BigIntegerField(blank=True, null=True)),
                ('trailing_pe', models.FloatField(blank=True, null=True)),
                ('forward_pe', models.FloatField(blank=True, null=True)),
                ('peg_ratio', models.FloatField(blank=True, null=True)),
                ('price_sales', models.FloatField(blank=True, null=True)),
                ('price_book', models.FloatField(blank=True, null=True)),
                ('ev_revenue', models.FloatField(blank=True, null=True)),
                ('ev_ebitda', models.FloatField(blank=True, null=True)),
                ('profit_margin', models.FloatField(blank=True, null=True)),
                ('return_on_assets', models.FloatField(blank=True, null=True)),
                ('return_on_equity', models.FloatField(blank=True, null=True)),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('net_income', models.BigIntegerField(blank=True, null=True)),
                ('diluted_eps', models.FloatField(blank=True, null=True)),
                ('total_cash', models.BigIntegerField(blank=True, null=True)),
                ('debt_to_equity', models.FloatField(blank=True, null=True)),
                ('levered_free_cash_flow', models.BigIntegerField(blank=True, null=True)),
                ('earnings_per_share', models.FloatField(blank=True, null=True)),
                ('price_to_earnings_ratio', models.FloatField(blank=True, null=True)),
                ('dividend_yield', models.FloatField(blank=True, null=True)),
                ('book_value', models.FloatField(blank=True, null=True)),
                ('debt_to_equity_ratio', models.FloatField(blank=True, null=True)),
                ('revenue_growth', models.FloatField(blank=True, null=True)),
                ('free_cash_flow', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
