# Generated by Django 5.0.6 on 2024-07-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_financialdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdata',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
