# Generated by Django 5.0.6 on 2024-07-04 21:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_financialdata_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp500ticker',
            name='logo_url',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
