# Generated by Django 5.0.6 on 2024-07-04 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0009_sp500ticker_logo_url_alter_financialdata_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sp500ticker',
            name='logo_url',
        ),
    ]
